-keep class com.smartcardpoc.** { *; }
-keep class android.hardware.usb.** { *; }
-keep class javax.smartcardio.** { *; }
-keep class com.abc.** { *; }
-dontwarn sun.security.action.**
-keep class sun.security.action.** { *; }