-keep class com.smartcardpoc.SmartCardModule { *; }
-keep class android.hardware.usb.** { *; }
-keep class javax.smartcardio.** { *; }
-dontwarn sun.security.action.**
-keep class sun.security.action.** { *; }